models:
  - name: dim_location
    description: "Location dimension"
    columns:
      - name: location_key
        description: The primary key for this table
        data_tests:
          - unique
          - not_null
      - name: incident_borough
      - name: zipcode
      - name: police_precinct
      - name: city_council_district
      - name: community_district
      - name: community_school_distric
      - name: congressional_district

  - name: dim_alarm
    description: "Alarm dimension"
    columns:
      - name: alarm_key
        description: The primary key for this table
        data_tests:
          - unique
          - not_null
      - name: alarm_box_borough
      - name: alarm_box_number
      - name: alarm_box_location
      - name: alarm_source_description
      - name: alarm_level_index_description
      - name: highest_alarm_level
      
  - name: dim_dates
    columns:
      - name: date_day
        description: The primary key for this table
        data_tests:
          - unique
          - not_null
      - name: day_of_week
      - name: day_of_month
      - name: day_of_year
      - name: week_of_year
      - name: month_of_year
      - name: month_name
      - name: quarter_of_year
      - name: year_number
      