fire_dispatch_modeling:
  outputs:
    dev:
      dataset: fdny_data_analysis
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: fdny-data-analysis
      threads: 10
      type: bigquery
  target: dev